### ISSUE TITLE
Suggestion of using badge to track stars

### ISSUE THREAD

**Issue by daochenzha** [wwxFromTju/awesome-reinforcement-learning-lib#3]
This a nice resource. But I feel like the stars of the projects could change over time and become hard to maintain. I suggest using badges so that they can be automatically updated. For example

<img class="badge svelte-bg3ukj" alt="GitHub Repo stars" src="https://img.shields.io/github/stars/wwxFromTju/awesome-reinforcement-learning-lib">

**Comment by wwxFromTju** [comment]
Thanks for your suggestion. Actually the raw data comes from my notion, so I am also looking for a good way to record the star.
